name: Nightly Build And Compile Test
  
on: 
  # Make sure it can be uploaded when a PR is requested - Vizonex
  pull_request:
    tags:
      - "*"
  workflow_dispatch: 
    
permissions:
  contents: read
  

jobs:
  build_wheels: 
    name: Build wheels 
    runs-on: windows-latest
        
    steps: 
      - uses: actions/checkout@v3 
        with:
          fetch-depth: 50
          submodules: true      

      - uses: actions/setup-python@v4 
        with: 
          python-version: "3.x"
  
      - name: Install cibuildwheel 
        run: pip install cibuildwheel -qq 
      
      
      - name: Build wheels 
        run: python -m cibuildwheel --output-dir wheelhouse 
        env: 
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-* cp313-*" 
          CIBW_SKIP: "pp* *-win_arm64 *-win32"

      - uses: actions/upload-artifact@v3 
        with: 
          name: dist
          path: ./wheelhouse/*.whl 
  
  
  build_sdist:
    name: Build source distribution
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
          submodules: true      
      
      - uses: actions/setup-python@v4 
        with: 
          python-version: "3.x"
          
      - name: Install Setuptools 
        run: python -m pip install --upgrade setuptools wheel pip cython
        
      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v3
        with:
          came: dist
          path: ./dist/*

  upload_wheels_as_nightly_builds:
      name: Publish
      needs: [build_wheels, build_sdist]
      runs-on: ubuntu-latest
  
      # I chose this repo's setup/workflow because it was the best Resource I could find for an implementation - Vizonex
      # See: https://github.com/hoffstadt/DearPyGui/blob/master/.github/workflows/Deployment.yml#L165 
      
      steps:
  
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Upload Nightly Builds
        uses: actions/upload-artifact@v3
        with:
          name: Winloop-Nightly-Wheels
          path: |
            "./wheelhouse/*.whl"
            "./dist/*"
